### ISSUE TITLE
[Feature]: 테스트 케이스 추출하기

### ISSUE THREAD

**Issue by SunwooJaeho** [kgu-dtcg/dtcg-client#91]
### Describe

현재 Result 값은 단순 테이블로 구현되어있지만 이를 변경하여 **option을 이용해 한 개의 테스트 케이스를 선택, '추출하기' 버튼을 클릭할 경우, Modal을 통해 해당 테스트 케이스를 사용자에게 보여주는 기능이에요.**

### Tasks

- [ ] 추출하기 버튼 생성
- [ ] Result 테이블 구조 변경 (인덱스마다 옵션 선택을 할 수 있도록 하는 형식, 복수 선택 불가.)
- [ ] 테스트 케이스 추출 기능

**Comment by gwansikk** [comment]
- https://github.com/kgu-dtcg/dtcg-client/issues/92

위 이슈 완료 후 개발을 진행합니다.
